[package]
name = "dagbog"
authors = ["Nikolaj J-K"]
description = "Redskab til at holde en dagbog"
repository = "https://github.com/jehaj/dagbog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
